#!/bin/bash

#SBATCH -A class
#SBATCH -N 1
#SBATCH --exclusive
#SBATCH --time=00:20:00

#SBATCH -J terasort
#SBATCH --error=terasort.%J.err
#SBATCH --output=terasort.%J.out

source /nethome/rvuduc3/local/jinx/setup-mpi.sh

make clean teragen terasort teravalidate

mpirun -np 16 ./teragen -f data.dat -c 1000

mpirun -np 16 ./terasort -f data.dat 

sleep 10

mpirun -np 16 ./teravalidate -f data.dat
